FROM ubuntu
ENV FORGE_VER=36.1.0 \
    MINECRAFT_VER=1.16.5
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get update && apt install default-jre -y
RUN apt install wget -y
WORKDIR /forge

RUN cd /
RUN mkdir forge
RUN cd forge
RUN wget https://maven.minecraftforge.net/net/minecraftforge/forge/1.16.5-36.1.0/forge-1.16.5-36.1.0-installer.jar
RUN java -jar forge-${MINECRAFT_VER}-${FORGE_VER}-installer.jar --installServer
RUN rm forge-1.16.5-36.1.0-installer.jar.log
RUN rm forge-1.16.5-36.1.0-installer.jar


CMD java -jar -Xmx2048m -Xms1024m forge-${MINECRAFT_VER}-${FORGE_VER}.jar
